title: CiviDraw
description: "토목 설계 자동화를 위한 CAD · Excel · HWP 솔루션"
url: "https://jong0342.github.io"
baseurl: ""

markdown: kramdown
kramdown:
  input: GFM

permalink: /:categories/:title/

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

defaults:
  - scope:
      path: ""
    values:
      sitemap: true
      image: /assets/og.png

exclude:
  - README.md
  - node_modules
  - vendor
  - Gemfile
  - Gemfile.lock

# Google Analytics 측정 ID (예: G-XXXXXXX)
google_analytics: G-BB7PYJSNK6
