title: CiviDraw
description: 토목 설계 자동화 CAD/Excel 솔루션
theme: jekyll-theme-cayman
url: https://jong0342.github.io
baseurl: ""        # username.github.io면 빈 값
author: jong0342
lang: ko
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
